# Generated by Django 3.2 on 2021-05-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natter', '0002_auto_20210529_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouproom',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='location',
        ),
    ]
