# Generated by Django 3.2 on 2021-05-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natter', '0004_auto_20210530_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouproom',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='is_verified',
        ),
    ]
