# Generated by Django 3.2 on 2021-05-30 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('natter', '0005_auto_20210530_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproom',
            name='room_name',
            field=models.SlugField(default=uuid.uuid4, max_length=250, null=True),
        ),
    ]
